#!/bin/bash

NOISE=0.3

#For all wheels
for i in {1..4}
do
	#Create a noise.ops file with the correct parameters
	case $i in
		1) echo "var array noise_min = array( -$NOISE, 0.0, 0.0, 0.0 )
var array noise_max = array( $NOISE, 0.0, 0.0, 0.0 )" > noise.ops;;
		2) echo "var array noise_min = array( 0.0, -$NOISE, 0.0, 0.0 )
var array noise_max = array( 0.0, $NOISE, 0.0, 0.0 )" > noise.ops;;
		3) echo "var array noise_min = array( 0.0, 0.0, -$NOISE, 0.0 )
var array noise_max = array( 0.0, 0.0, $NOISE, 0.0 )" > noise.ops;;
		4) echo "var array noise_min = array( 0.0, 0.0, 0.0, -$NOISE )
var array noise_max = array( 0.0, 0.0, 0.0, $NOISE )" > noise.ops;;
		*) echo 'Error!'; return;;
	esac
	cat `rospack find amigo_base_controller`/identification/base_identification.ops >> noise.ops
	sed -i "s|/tmp/wheel.dat|/tmp/wheel$i.dat|g" noise.ops
	
	#Run the identification
	rosrun ocl deployer-gnulinux -s `rospack find amigo_etherCAT`/soem.ops -s `rospack find amigo_base_controller`/base_controller.ops -s `rospack find amigo_base_controller`/identification/noise.ops 
	
	#Sleep a bit so people have time to press ctrl+c
	sleep 1
done
