#!/bin/bash

#Create a ramdisk to allow fast writing of the report file.
sudo mkdir -p /tmp/ramdisk
#Allow full acces
sudo chmod 777 /tmp/ramdisk
#Mount a piece of ram here
sudo mount -t tmpfs -o size=256M tmpfs /tmp/ramdisk/


	cat `rospack find amigo_base_controller`/identification/test.ops >> test2.ops
	sed -i 's|/home/tim/reports.dat|/tmp/ramdisk/reports.dat|g' test2.ops
	
	#Run the identification with a timeout.
	timeout 5 rosrun ocl deployer-gnulinux -s test2.ops
	
	#move .dat file to disk
	mv /tmp/ramdisk/reports.dat /home/tim/reportsram.dat

